CONFIG_LOG=y
CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_OFF=y

# Wi-Fi Configuration
CONFIG_WIFI=y
CONFIG_WIFI_NM=y
CONFIG_WIFI_USAGE_MODE_STA_AP=y

# Network Configuration
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV4_SERVER=y
# 由4改为1，后期出问题可以检查
CONFIG_NET_DHCPV4_SERVER_ADDR_COUNT=1
CONFIG_NET_IF_MAX_IPV4_COUNT=2
CONFIG_NET_IPV4=y
# 暂时不连接公网 WIFI，关闭 IPV6
CONFIG_NET_IPV6=n
# CONFIG_NET_IF_MAX_IPV6_COUNT=2
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=10
CONFIG_NET_MGMT_EVENT_STACK_SIZE=4096
CONFIG_NET_PKT_RX_COUNT=16
CONFIG_NET_PKT_TX_COUNT=16
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=4096
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NETWORKING=y

# LOG Configuration
CONFIG_NET_LOG=y
CONFIG_NET_DHCPV4_SERVER_LOG_LEVEL_DBG=y

CONFIG_WIFI_ESP32=y
CONFIG_WIFI_AP_SSID="FlowInk-AP"
CONFIG_WIFI_AP_PSK="hhhhhhhh"
CONFIG_WIFI_AP_IP_ADDRESS="192.168.4.1"
CONFIG_WIFI_AP_NETMASK="255.255.255.0"




# General config
CONFIG_MAIN_STACK_SIZE=3072
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_INIT_STACKS=y

# Networking config
CONFIG_NET_SOCKETS=y
CONFIG_NET_SHELL=y

# JSON
CONFIG_JSON_LIBRARY=y

# HTTP parser
CONFIG_HTTP_PARSER_URL=y
CONFIG_HTTP_PARSER=y
CONFIG_HTTP_SERVER=y

# Network buffers
CONFIG_NET_BUF_RX_COUNT=128
CONFIG_NET_BUF_TX_COUNT=128
CONFIG_NET_CONTEXT_NET_PKT_POOL=y

# IP address options
CONFIG_NET_MAX_CONTEXTS=32
CONFIG_NET_MAX_CONN=32

# Network address config
CONFIG_NET_CONFIG_SETTINGS=y
# CONFIG_NET_CONFIG_NEED_IPV4=y
# CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"
# CONFIG_NET_CONFIG_PEER_IPV4_ADDR="192.0.2.2"
# CONFIG_NET_CONFIG_MY_IPV4_GW="192.0.2.2"

# Networking tweaks
# Required to handle large number of consecutive connections,
# e.g. when testing with ApacheBench.
CONFIG_NET_TCP_TIME_WAIT_DELAY=0

# Network debug config
CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=n
CONFIG_NET_HTTP_LOG_LEVEL_DBG=n


# 1. 网络缓冲区大小前后不一致（内存浪费）
# 上方：
# conf
# CONFIG_NET_PKT_RX_COUNT=16
# CONFIG_NET_PKT_TX_COUNT=16
# 下方重复定义更大的值：
# conf
# CONFIG_NET_BUF_RX_COUNT=128
# CONFIG_NET_BUF_TX_COUNT=128
# 后面的配置会覆盖前面，缓冲区开到 128 偏大，单纯局域网 HTTP 控制灯带完全不需要，白白占用大量 RAM，容易造成内存紧张。
# 2. 开启了无用 CONFIG_NET_L2_ETHERNET=y
# 你使用 WiFi 联网，没有以太网硬件，开启以太网二层驱动只会加载无用代码、占用 Flash 与内存，建议关闭。
# 3. CONFIG_NET_SHELL=y 开启网络命令行 shell
# 你不需要串口输入网络调试命令，开启会额外占用栈与内存，可关闭。
# 4. CONFIG_NET_TCP_TIME_WAIT_DELAY=0 压测专用参数
# 该配置仅用于 ab 并发压测消除 TIME_WAIT 连接堆积，普通家用手机访问网页场景不需要；设为 0 在频繁断开重连时可能造成 TCP 端口异常复用，删掉该行即可使用系统默认值。
# 5. DHCP 服务器开启调试日志 CONFIG_NET_DHCPV4_SERVER_LOG_LEVEL_DBG=y
# 热点接入设备较多时会疯狂打印 DHCP 调试日志，刷屏浪费串口带宽、消耗 CPU，建议改成 =n。
# 6. CONFIG_NET_L2_ETHERNET=y 以太网驱动开启，无硬件冗余
# ESP32 方案无网口，直接注释关闭。
# 7. CONFIG_NET_UDP=y 多余开启
# 你的业务只有 HTTP (TCP)，没有 UDP 业务，可关闭节省资源；保留也不会出错。
# 8. 数值偏大的网络上下文连接数
# CONFIG_NET_MAX_CONTEXTS=32、CONFIG_NET_MAX_CONN=32，家用最多同时 3~5 台手机接入，可下调至 16。

