CONFIG_LOG=y
CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_OFF=y
CONFIG_INPUT=y
CONFIG_SPI=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_FILE_SYSTEM=y
# FAT32
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS=y
CONFIG_FS_FATFS_FSTAB_AUTOMOUNT=y