CONFIG_LOG=y
CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_OFF=y
CONFIG_INPUT=y
CONFIG_WIFI=y                                 # Wi-Fi 子系统总开关
CONFIG_NET_L2_WIFI_MGMT=y                     # 允许应用层发送 Wi-Fi 控制命令（如启动 AP）
CONFIG_NETWORKING=y                           # Zephyr 网络栈总开关
CONFIG_NET_IPV4=y                             # 启用 IPv4 协议
CONFIG_NET_TCP=y                              # 启用 TCP 协议
CONFIG_NET_L2_ETHERNET=y                      # 启用以太网 L2 层（Wi-Fi 在 Zephyr 中抽象为以太网接口）
CONFIG_NET_DHCPV4_SERVER=y                    # 【核心】启用 DHCP 服务器，给连接的设备分配 IP
CONFIG_NET_IF_MAX_IPV4_COUNT=1                # 仅需 1 个 IPv4 接口（AP 接口）
CONFIG_NET_IF_MAX_IPV6_COUNT=0                # 无 IPv6 需求
CONFIG_NET_PKT_RX_COUNT=16                    # 接收数据包缓冲池
CONFIG_NET_PKT_TX_COUNT=16                    # 发送数据包缓冲池
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=4096    # Socket 服务线程栈
CONFIG_NET_LOG=y                              # 网络日志